# Generated by Django 6.0.5 on 2026-05-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_room_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
